version: '3.8'

services:
  backend:
    container_name: backend
    # image: new-image
    depends_on:
      - db
    build: .
    env_file: .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - anterebol
  db: 
    container_name: db
    build: ./database
    # image: postrgres:14.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    # PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - anterebol
    
networks:
  anterebol: